### ISSUE TITLE
Display Broken on Macbook Pro Safari

### ISSUE THREAD

**Issue by popaquet** [danielkorte/QueueSlider#2]
The slider does not display correctly on MacBook OS V. 10.8.5.

When we reduce the size of the windows the problem is solved !

**Comment by danielkorte** [comment]
Thanks for the note, but I'm unable to reproduce this issue in Browserstack.

If you'd like to provide more information such as screenshots, Safari version, etc. feel free to do so. Also, check that you have all Safari extensions disabled and you have a clean cache.
